language: python

# Use container-based infrastructure
sudo: false

# Services
services:
  - elasticsearch

# Package installation
install:
  - pip install -r requirements.txt

# Pre-test configuration
#before_script:
  #- python cycleangel/manage.py test

script:
  - "python cycleangel/manage.py test"

# Who to notify about build results
notifications:
  email:
    recipients:
      - travis@zrmt.com
    on_success: change
    on_failure: always
# bump Travis: 1
